services:
  node1:
    build: .
    container_name: mcast-node1
    networks:
      labnet:
        ipv4_address: 172.28.0.11
    tty: true

  node2:
    build: .
    container_name: mcast-node2
    networks:
      labnet:
        ipv4_address: 172.28.0.12
    tty: true

  node3:
    build: .
    container_name: mcast-node3
    networks:
      labnet:
        ipv4_address: 172.28.0.13
    tty: true

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24